#!/usr/bin/env python

from setuptools import setup, find_packages, Extension

_wiringpi2 = Extension(
    '_wiringpi2',
    sources=[
	'WiringPi/wiringPi/wiringPi.c',
        'WiringPi/wiringPi/wiringPiSPI.c',
        'WiringPi/wiringPi/max31855.c',
        'WiringPi/wiringPi/max5322.c',
        'WiringPi/wiringPi/drc.c',
        'WiringPi/wiringPi/sn3218.c',
        'WiringPi/wiringPi/mcp23s17.c',
        'WiringPi/wiringPi/pcf8591.c',
        'WiringPi/wiringPi/softTone.c',
        'WiringPi/wiringPi/wiringSerial.c',
        'WiringPi/wiringPi/mcp23008.c',
        'WiringPi/wiringPi/mcp3002.c',
        'WiringPi/wiringPi/mcp3004.c',
        'WiringPi/wiringPi/piHiPri.c',
        'WiringPi/wiringPi/sr595.c',
        'WiringPi/wiringPi/wiringShift.c',
        'WiringPi/wiringPi/mcp23016.c',
        'WiringPi/wiringPi/mcp3422.c',
        'WiringPi/wiringPi/piThread.c',
        'WiringPi/wiringPi/mcp23017.c',
        'WiringPi/wiringPi/mcp4802.c',
        'WiringPi/wiringPi/softPwm.c',
        'WiringPi/wiringPi/wiringPiI2C.c',
        'WiringPi/wiringPi/mcp23s08.c',
        'WiringPi/wiringPi/pcf8574.c',
        'WiringPi/wiringPi/softServo.c',
        'WiringPi/devLib/ds1302.c',
        'WiringPi/devLib/lcd128x64.c',
        'WiringPi/devLib/maxdetect.c',
        'WiringPi/devLib/gertboard.c',
        'WiringPi/devLib/lcd.c',
        'WiringPi/devLib/piFace.c',
        'WiringPi/devLib/piNes.c',
        'WiringPi/devLib/piGlow.c',
        'wiringpi_wrap.c'
    ],
)

setup(
    name = 'wiringpi2',
    version = '1.0.10',
    author = "Philip Howard",
    author_email = "phil@gadgetoid.com",
    url = 'https://github.com/Gadgetoid/WiringPi2-Python/',
    description = """A python interface to WiringPi 2.0 library which allows for
    easily interfacing with the GPIO pins of the Raspberry Pi. Also supports
    i2c and SPI""",
    long_description=open('README').read(),
    ext_modules = [ _wiringpi2 ],
    py_modules = ["wiringpi2"],
    install_requires=[],
    headers=[
	'WiringPi/wiringPi/wiringPi.h',
        'WiringPi/wiringPi/wiringPiI2C.h',
        'WiringPi/wiringPi/max31855.h',
        'WiringPi/wiringPi/max5322.h',
        'WiringPi/wiringPi/drc.h',
        'WiringPi/wiringPi/sn3218.h',
        'WiringPi/wiringPi/mcp23s08.h',
        'WiringPi/wiringPi/mcp3422.h',
        'WiringPi/wiringPi/softServo.h',
        'WiringPi/wiringPi/wiringPiSPI.h',
        'WiringPi/wiringPi/mcp23008.h',
        'WiringPi/wiringPi/mcp23s17.h',
        'WiringPi/wiringPi/mcp4802.h',
        'WiringPi/wiringPi/softTone.h',
        'WiringPi/wiringPi/wiringSerial.h',
        'WiringPi/wiringPi/mcp23016.h',
        'WiringPi/wiringPi/mcp23x0817.h',
        'WiringPi/wiringPi/pcf8574.h',
        'WiringPi/wiringPi/sr595.h',
        'WiringPi/wiringPi/wiringShift.h',
        'WiringPi/wiringPi/mcp23016reg.h',
        'WiringPi/wiringPi/mcp23x08.h',
        'WiringPi/wiringPi/pcf8591.h',
        'WiringPi/wiringPi/mcp23017.h',
        'WiringPi/wiringPi/mcp3002.h',
        'WiringPi/wiringPi/mcp3004.h',
        'WiringPi/wiringPi/softPwm.h',
        'WiringPi/devLib/ds1302.h',
        'WiringPi/devLib/gertboard.h',
        'WiringPi/devLib/lcd.h',
        'WiringPi/devLib/piFace.h',
        'WiringPi/devLib/font.h',
        'WiringPi/devLib/lcd128x64.h',
        'WiringPi/devLib/maxdetect.h',
        'WiringPi/devLib/piNes.h'
        'WiringPi/devLib/piGlow.h',
        ]
)
